### ISSUE TITLE
Will the statement be printed to the console? (if else)

### ISSUE THREAD

**Issue by kibin** [mosaic-academy/exercises#3]
```
if (typeof 'yen' !== 'String') {
  console.log('Message');
}
```

The answer is yes because `typeof 'yen'` will produce `'string'` lowercased. But:

![arsnt](https://cloud.githubusercontent.com/assets/1782569/7896861/4833e2ca-06d0-11e5-884c-4795b727d6bb.png)

**Comment by tiery** [comment]
Same here :

![mosaic-academy-bug](https://cloud.githubusercontent.com/assets/749255/7901258/e1c10c3e-077e-11e5-92b6-f107fe2d6850.jpg)

**Comment by tiery** [comment]
great :)
